# Generated by Django 2.1.4 on 2018-12-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0002_piclab_staff'),
    ]

    operations = [
    ]
