# Generated by Django 2.1.4 on 2018-12-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learn', '0003_auto_20181216_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='TelNum',
            field=models.CharField(default='', max_length=20),
        ),
    ]
